spin_manifest_version = 2

[application]
name = "spin-todo-api"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-todo-api"

[component.spin-todo-api]
source = "target/wasm32-wasip1/release/spin_todo_api.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.spin-todo-api.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
